### ISSUE TITLE
Register Napari.jl and method proposal

### ISSUE THREAD

**Issue by roflmaostc** [mkitti/Napari.jl#10]
Hey,

thanks for the package! I'm using it daily and would be happy if you could register it? Makes it much easier for me to include it into examples etc.

I was also wondering if I could propose a method? I'm using often something like this: 
```
function view_images(img...)
     napari.view_image(permutedims(cat(himg..., dims=3), (3,2,1)))
end
```
Am I overlooking something or does it only work like this?

Thanks,

Felix

**Comment by mkitti** [comment]
Hi Felix,

Thanks for the feedback.

I'm working on https://github.com/JuliaPy/PyCall.jl/pull/876 over at PyCall.jl at the moment. That would allow `PermuteDimsArray` to be used to create a _view_ of the underlying array rather than making a copy.

For the proposed `view_images`, could you tell me about the type of `img` or `himg` and describe what is the third dimension?

-Mark

**Comment by roflmaostc** [comment]
`view_images` takes 2D arrays as input. I believe napari expects the _stack dimension _ (to use the slider) at dimension 1.
Often I want to compare images by using the slider and a certain region. Hence I need to concat them and permute dims.

**Comment by mkitti** [comment]
I would take a look at the `order` property of `Viewer` which you can also provide as a keyword to `view_image`: https://napari.org/docs/0.4.3/api/napari.html?highlight=view_image#napari.view_image

Note that `order` is a property of `Viewer` and not the image layer. If you use `add_image` to add images the viewer, then they will use the order that you initialized when you created the viewer with `view_image`.

Also if your your image is of type `AxisArray` I do some dimension permutation to move the `:time` and `:channel` axes as the first channels.
https://github.com/mkitti/Napari.jl/blob/main/src/image.jl#L111

**Comment by mkitti** [comment]
On the register Napari.jl I have most of the commits I want in pushed now. I would like to setup continuous integration though.

**Comment by mkitti** [comment]
I'm getting closer on registering this package. I could use some help reviewing the README.md documentation for accuracy.

How well does the install go for you?

**Comment by roflmaostc** [comment]
Yesterday I installed PyCall and napari on a new machine, it also worked with pip.

However, I didn't test the more advanced features mentioned in the documentation below

**Comment by mkitti** [comment]
Did you install Napari first before Napari.jl or did you let Napari.jl install Napari?

**Comment by roflmaostc** [comment]
I believe I tried both.

But I struggled first because the recent Napari is broken with a certain Dependency 🙄

**Comment by mkitti** [comment]
Registration PR: https://github.com/JuliaRegistries/General/pull/31480
